name: README Info Update

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - uses: th3c0d3br34ker/github-readme-info@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: 'Asia/Seoul'
          SHOW_LINES_OF_CODE: 'False'
          SHOW_PROFILE_VIEWS: 'True'
          SHOW_DAILY_COMMIT: 'True'
          SHOW_WEEKLY_COMMIT: 'True'
          SHOW_LANGUAGE: 'True'
          SHOW_TOTAL_CONTRIBUTIONS: 'False'
